### ISSUE TITLE
native extensions fail to build

### ISSUE THREAD

**Issue by kangguru** [pkgr/rubies#4]
maybe i'm just holding it wrong :) 

installing the ruby works just fine, but when i try to install gems with native extensions, things start to go wrong:

https://gist.github.com/kangguru/c5b1219433d2044e10cd

the readme says that it will ship with static compiled versions of libffi und others, so maybe i need to set some flags?

on the other side

https://packager.io/gh/pkgr/rubies/build_runs/29#8012

states this: `ffi.h is missing. Please install libffi.`

what can i do?

**Comment by kangguru** [comment]
i was missing `libjemalloc-dev` on the machine :( 

sorry for bothering

**Comment by crohr** [comment]
Thanks for letting me know. Was the lib you installed (libjemalloc-dev) related to the gem you wanted to build?

**Comment by kangguru** [comment]
i was misled by the error message i saw, but once i looked into the `mkmf.log` things got clearer, `ld` failed b/c of not finding jemalloc and installing it solved the issue!

btw. packacker.io just saved my day :D
